### ISSUE TITLE
Chain download failed.

### ISSUE THREAD

**Issue by Tectract** [hyperledger/besu#992]
### Description
Trying to start a second IBFT node, to connect to my first bootnode, fails.

### Acceptance Criteria
Blockchain startup / setup troubleshooting

### Steps to Reproduce (Bug)
1. Start IBFT boot node (N1) according to docs tutorial (everything seems to start ok, blocks are being generated)
2. Start IBFT peer node (N2) according to docs tutorial 

**Expected behavior:** [What you expect to happen]
Node N2 should be downloading and verifying blocks from N1 until they are synced, downloading the chain.

**Actual behavior:** [What actually happens]

(chain fails to download)

    2020-05-27 22:33:41.079-06:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saving announced block 18 (0x0be9ff1d4d9adedaeafb7677ef2bf2bc966486ee3acd3efe5605bc9e9815ce9b) for future import
    2020-05-27 22:33:43.887-06:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer 0xfe639f8c0e7fc79ffd... at block 0
    2020-05-27 22:33:43.954-06:00 | EthScheduler-Services-2 (validateHeadersJoin) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
    java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
	at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
    Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:141) ~[?:?]
	at 
    org.hyperledger.besu.ethereum.eth.sync.CheckpointRange.getEnd(CheckpointRange.java:58) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:50) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:26) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.FlatMapProcessor.processNextInput(FlatMapProcessor.java:32) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	... 5 more

**Frequency:** [What percentage of the time does it occur?]
(always)

### Versions (Add all that apply)
* Software version: [`besu --version`]

besu/v1.4.6-dev-ffa8745d/linux-x86_64/zulu-java-13

* Java version: [`java -version`]

openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)

* OS Name & Version: [`cat /etc/*release`]

Linux Mint 17 Qiana

* Kernel Version: [`uname -a`]

based on Ubuntu 14.04

(standalone machines)

### Additional Information

Please let me know any additional troubleshooting steps or info I can provide. Thanks all~

**Comment by NicolasMassart** [comment]
Hi,
could you provide the following info please:
- exact command lines used to run both nodes.
- genesis file used by both nodes.
- logs of Node1 up to the moment Node2 crashes.

Thank you.

**Comment by Tectract** [comment]
1. command used to run bootnode N1:
    besu --genesis-file=/path/to/GBA_IBFT_genesis.json --p2p-host="N2.server.external.IPaddress"
command used to run peer node N2:
    besu --genesis-file=/path/to/GBA_IBFT_genesis.json

I put the enode address from bootnode N1 into a file static-nodes.json, on peer node N2.

2. genesis file

    {
      "config": {
        "chainId": 2020,
        "constantinoplefixblock": 0,
        "ibft2": {
          "blockperiodseconds": 5,
          "epochlength": 30000,
          "requesttimeoutseconds": 10
        }
      },
      "nonce": "0x0",
      "timestamp": "0x58ee40ba",
      "extraData": "0xf83ea00000000000000000000000000000000000000000000000000000000000000000d5943aadaa7834ee17873396d7c2a5153549e7730eaa8084000$
      "gasLimit": "0x1fffffffffffff",
      "difficulty": "0x1",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "coinbase": "0x0000000000000000000000000000000000000000",
      "alloc": {}
    }

3. Here are the logs from the bootnode, as I attempt to connect the peer node. It shows no errors.

2020-05-27 22:36:12.947-06:00 | main | INFO  | Besu | Starting Besu version: besu/v1.4.1-dev-ad5bfecd/linux-x86_64/zulu-java-13
2020-05-27 22:36:13.144-06:00 | main | INFO  | StaticNodesParser | StaticNodes file /path/to/build/install/besu/static-nodes.json does not exist, no static connections will be created.
2020-05-27 22:36:13.144-06:00 | main | INFO  | Besu | Connecting to 0 static nodes.
2020-05-27 22:36:13.735-06:00 | main | INFO  | KeyPairUtil | Loaded key 0xfe639f8c0e7fc79ffd6eacbe7f49e82bba28a42b5a899c8f72694865b4d752d88ca050f866d36cf2856ad6bff3c3bb47ba46933fc30f81e3fcb715797985a929 from /path/to/build/install/besu/key
2020-05-27 22:36:13.753-06:00 | main | INFO  | RocksDBKeyValueStorageFactory | No existing database detected at /path/to/build/install/besu. Using version 1
2020-05-27 22:36:14.553-06:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [ConstantinopleFix: 0]
2020-05-27 22:36:14.652-06:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2020-05-27 22:36:14.703-06:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
2020-05-27 22:36:14.703-06:00 | main | INFO  | NatService | No NAT environment detected so no service could be started
2020-05-27 22:36:14.704-06:00 | main | INFO  | NetworkRunner | Starting Network.
2020-05-27 22:36:14.773-06:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0:0:0:0:0:0:0:0:30303.
2020-05-27 22:36:14.773-06:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2020-05-27 22:36:14.815-06:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0:0:0:0:0:0:0:0 and port=30303
2020-05-27 22:36:14.818-06:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0:0:0:0:0:0:0:0:30303
2020-05-27 22:36:14.846-06:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://fe639f8c0e7fc79ffd6eacbe7f49e82bba28a42b5a899c8f72694865b4d752d88ca050f866d36cf2856ad6bff3c3bb47ba46933fc30f81e3fcb715797985a929@N2.server.external.IPaddress:30303
2020-05-27 22:36:14.849-06:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2020-05-27 22:36:14.851-06:00 | main | INFO  | FullSyncDownloader | Start full sync.
2020-05-27 22:36:14.853-06:00 | main | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:14.893-06:00 | main | INFO  | Runner | Ethereum main loop is up.
2020-05-27 22:36:14.898-06:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
2020-05-27 22:36:14.979-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=1, Round=0}, hash=0xa72bf12a95f5b9382452f0180ea76923e4f12ff5cf574bcfd511fb2157916b1c
2020-05-27 22:36:19.046-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=2, Round=0}, hash=0xf403b035c84424a1d7ff8aa667f63274bdaa5604d01217d6c0816c298dd7d5ac
2020-05-27 22:36:19.861-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:24.046-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=3, Round=0}, hash=0x93e98adb83a909719ad5a0049aa09d55f715f72c8a5b23ec3288e2d3b202a8df
2020-05-27 22:36:24.862-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:29.029-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=4, Round=0}, hash=0x71b27c6e354f5e9e4a13da7dbb703c5b4def23693db3f8f1b30a8e6b6d4aeee9
2020-05-27 22:36:29.863-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:34.027-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=5, Round=0}, hash=0xc40512cc70c6587c3d1eb96fbd4d00eaea42ff85f6ff49acb6f32bba00dd4385
2020-05-27 22:36:34.863-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:39.029-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=6, Round=0}, hash=0x728568dbbf38dec75101fb6ab5d06e1ced54a0ff377e4a3abf9ad1672e7f5973
2020-05-27 22:36:39.864-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.013-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.014-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.014-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.014-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.014-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.015-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.015-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.015-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:40.015-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:44.025-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=7, Round=0}, hash=0x27d583d6ac6997f42589da9680747d60f3beb2a1a280f0470b53e56ea839969d
2020-05-27 22:36:45.016-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:49.026-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=8, Round=0}, hash=0x6642a218b421771ac644d4a6e6a575cb05b9b4a4553fff03230320e1071ce601
2020-05-27 22:36:50.016-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:54.029-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=9, Round=0}, hash=0xc87f81e852fdf54b288889cb03776a8002de7226772e71d8b3111207f183d755
2020-05-27 22:36:55.017-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:36:59.023-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=10, Round=0}, hash=0x20de4351eb96fb9b6a89a7fcbf8213409c53b74dcaba1cc7082a4067b3681281
2020-05-27 22:37:00.018-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:37:04.021-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=11, Round=0}, hash=0xbb7572c5debb5671bb445ae924ddf8de837192b1f879305af8ee8404f00d9564
2020-05-27 22:37:05.018-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:37:09.020-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=12, Round=0}, hash=0xdf92a69735688832b8f01a19de47a46ca4941dd012b64f2b4021cf0722c215d4
2020-05-27 22:37:10.019-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:37:14.022-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=13, Round=0}, hash=0x1dbb4182615c2ff0146db39efdb0da523f13be2ce3b9227ce86b4ac7897a54be
2020-05-27 22:37:15.019-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:37:19.023-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=14, Round=0}, hash=0xc94112758adebb2ffd27c88870e20f153e7b8598b9ca1288e932371d84c8c276
2020-05-27 22:37:20.020-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:37:24.023-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=15, Round=0}, hash=0xabd6ae2030d485dbc60fc077e3cc637fe225f8783f621f01997e22f24cd204e9
2020-05-27 22:37:25.021-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-27 22:37:29.023-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=16, Round=0}, hash=0x54db80a06cbec95a1edfc42302f36977c7fd33efe9967ef0a6698297ea5b34c0
2020-05-27 22:37:30.021-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
^C2020-05-27 22:37:31.028-06:00 | pool-10-thread-1 | INFO  | IbftProcessor | Shutting down IBFT event processor
2020-05-27 22:37:31.030-06:00 | Thread-1 | INFO  | DefaultSynchronizer | Stopping synchronizer
2020-05-27 22:37:31.031-06:00 | Thread-1 | INFO  | NetworkRunner | Stopping Network.
2020-05-27 22:37:31.036-06:00 | Thread-1 | INFO  | EthProtocolManager | Stopping eth Subprotocol.
2020-05-27 22:37:31.037-06:00 | Thread-1 | INFO  | EthProtocolManager | eth Subprotocol stopped.
2020-05-27 22:37:31.037-06:00 | Thread-1 | INFO  | NetworkRunner | Network stopped.
2020-05-27 22:37:31.037-06:00 | Thread-1 | INFO  | AutoTransactionLogBloomCachingService | Shutting down Auto transaction logs caching service.
2020-05-27 22:37:31.038-06:00 | Thread-1 | INFO  | NatService | No NAT environment detected so no service could be stopped

4. Tutorial address:

https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

and 

https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/IBFT/


5. Here's what I see on the peer node:

2020-05-27 22:33:26.908-06:00 | main | INFO  | AltBN128PairingPrecompiledContract | Using native alt bn128
2020-05-27 22:33:27.620-06:00 | main | INFO  | SECP256K1 | Using native secp256k1
2020-05-27 22:33:27.627-06:00 | main | INFO  | Besu | Starting Besu version: besu/v1.4.6-dev-ffa8745d/linux-x86_64/zulu-java-13
2020-05-27 22:33:28.028-06:00 | main | INFO  | Besu | Connecting to 1 static nodes.
2020-05-27 22:33:28.038-06:00 | main | INFO  | Besu | Security Module: localfile
2020-05-27 22:33:28.100-06:00 | main | INFO  | KeyPairUtil | Loaded public key 0xbf3f0cdcafe2f58b214f9f15027904b2bef37a9f6f6b0b1113ce11e09b298c61353c6acaa173f56362ec32f4ebd1474c876bfd1932eb596b10a64cf6930a37fe from /path/to/build/install/besu/key
2020-05-27 22:33:28.135-06:00 | main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /path/to/build/install/besu
2020-05-27 22:33:28.204-06:00 | main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /path/to/build/install/besu. Version 1
2020-05-27 22:33:28.582-06:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [ConstantinopleFix: 0]
2020-05-27 22:33:28.739-06:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2020-05-27 22:33:28.818-06:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
2020-05-27 22:33:28.819-06:00 | main | INFO  | NatService | No NAT environment detected so no service could be started
2020-05-27 22:33:28.819-06:00 | main | INFO  | NetworkRunner | Starting Network.
2020-05-27 22:33:28.922-06:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0:0:0:0:0:0:0:0:30303.
2020-05-27 22:33:28.923-06:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2020-05-27 22:33:28.990-06:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0:0:0:0:0:0:0:0 and port=30303
2020-05-27 22:33:28.991-06:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0:0:0:0:0:0:0:0:30303
2020-05-27 22:33:29.056-06:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://bf3f0cdcafe2f58b214f9f15027904b2bef37a9f6f6b0b1113ce11e09b298c61353c6acaa173f56362ec32f4ebd1474c876bfd1932eb596b10a64cf6930a37fe@127.0.0.1:30303
2020-05-27 22:33:29.057-06:00 | main | INFO  | DefaultP2PNetwork | Node address 0x4d67bc82a63dc4837b966b9219bdb247c392b255
2020-05-27 22:33:29.062-06:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2020-05-27 22:33:29.066-06:00 | main | INFO  | FullSyncDownloader | Starting full sync.
2020-05-27 22:33:29.069-06:00 | main | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2020-05-27 22:33:29.112-06:00 | main | INFO  | Runner | Ethereum main loop is up.
2020-05-27 22:33:29.119-06:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
2020-05-27 22:33:34.083-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2020-05-27 22:33:38.878-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.879-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.879-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.880-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.880-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.880-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.881-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.881-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.882-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.882-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.883-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:38.883-06:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-27 22:33:41.079-06:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saving announced block 18 (0x0be9ff1d4d9adedaeafb7677ef2bf2bc966486ee3acd3efe5605bc9e9815ce9b) for future import
2020-05-27 22:33:43.887-06:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer 0xfe639f8c0e7fc79ffd... at block 0
2020-05-27 22:33:43.954-06:00 | EthScheduler-Services-2 (validateHeadersJoin) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
	at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:141) ~[?:?]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointRange.getEnd(CheckpointRange.java:58) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:50) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:26) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.FlatMapProcessor.processNextInput(FlatMapProcessor.java:32) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	... 5 more

 

Since the actual first line of the error is hidden by the "... 5 more" thing, I can only gleam here that something has gone wrong in the validateHeadersJoin() function call. It appears that it has tried to read past the end of an array, or returned null where data was expected.

**Comment by NicolasMassart** [comment]
You node 2 log shows that you already have a database.
```
2020-05-27 22:33:28.135-06:00 | main | INFO | DatabaseMetadata | Lookup database metadata file in data directory: /path/to/build/install/besu
2020-05-27 22:33:28.204-06:00 | main | INFO | RocksDBKeyValueStorageFactory | Existing database detected at /path/to/build/install/besu. Version 1
```
Could you try to remove the datas before running it just to exclude the fact that the current DB could be the issue please?
in your data directory, run: 
`rm -Rf DATABASE_METADATA.json caches database`

**Comment by Tectract** [comment]
Thank you for this suggestion, but alas it did not solve the problem. I'm getting the same error after removing those files/folders from both nodes and restarting, first the boot node and then the peer. 

Boot node:

2020-05-29 15:11:27.515-06:00 | main | INFO  | Besu | Starting Besu version: besu/v1.4.1-dev-ad5bfecd/linux-x86_64/zulu-java-13
2020-05-29 15:11:27.712-06:00 | main | INFO  | StaticNodesParser | StaticNodes file /path/to/build/install/besu/static-nodes.json does not exist, no static connections will be created.
2020-05-29 15:11:27.712-06:00 | main | INFO  | Besu | Connecting to 0 static nodes.
2020-05-29 15:11:28.306-06:00 | main | INFO  | KeyPairUtil | Loaded key 0xfe639f8c0e7fc79ffd6eacbe7f49e82bba28a42b5a899c8f72694865b4d752d88ca050f866d36cf2856ad6bff3c3bb47ba46933fc30f81e3fcb715797985a929 from /path/to/build/install/besu/key
2020-05-29 15:11:28.323-06:00 | main | INFO  | RocksDBKeyValueStorageFactory | No existing database detected at /path/to/build/install/besu. Using version 1
2020-05-29 15:11:29.090-06:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [ConstantinopleFix: 0]
2020-05-29 15:11:29.188-06:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2020-05-29 15:11:29.243-06:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
2020-05-29 15:11:29.244-06:00 | main | INFO  | NatService | No NAT environment detected so no service could be started
2020-05-29 15:11:29.244-06:00 | main | INFO  | NetworkRunner | Starting Network.
2020-05-29 15:11:29.315-06:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0:0:0:0:0:0:0:0:30303.
2020-05-29 15:11:29.316-06:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2020-05-29 15:11:29.362-06:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0:0:0:0:0:0:0:0 and port=30303
2020-05-29 15:11:29.365-06:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0:0:0:0:0:0:0:0:30303
2020-05-29 15:11:29.394-06:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://fe639f8c0e7fc79ffd6eacbe7f49e82bba28a42b5a899c8f72694865b4d752d88ca050f866d36cf2856ad6bff3c3bb47ba46933fc30f81e3fcb715797985a929@N2.node.external.IPaddress:30303
2020-05-29 15:11:29.397-06:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2020-05-29 15:11:29.398-06:00 | main | INFO  | FullSyncDownloader | Start full sync.
2020-05-29 15:11:29.400-06:00 | main | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:11:29.438-06:00 | main | INFO  | Runner | Ethereum main loop is up.
2020-05-29 15:11:29.443-06:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
2020-05-29 15:11:29.527-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=1, Round=0}, hash=0xc337fecaf28ce0aa559be50a965acc88143d37e0d10bec8085b8a4c3236353af
2020-05-29 15:11:34.056-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=2, Round=0}, hash=0x4002ca6181d6952799d53ca6cf308cab0818862737be4c92e6b95cc0cf2dec31
2020-05-29 15:11:34.408-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:11:39.026-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=3, Round=0}, hash=0x550076867abf0d78c2da343022ef5f949fa846c9094b4d7f4ed187e31e57ac15
2020-05-29 15:11:39.409-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:11:44.029-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=4, Round=0}, hash=0xb9967cf19e3e9822e23bd7a49bd69c4a0da1c5d0890b7ce6a6a3cbea7f62af5a
2020-05-29 15:11:44.409-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:11:49.025-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=5, Round=0}, hash=0x0cd8a644a5db12de5b562bed1ab08446c956dead20a7dbdc5bcd534a4a7a6a10
2020-05-29 15:11:49.410-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:11:54.027-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=6, Round=0}, hash=0xd86864f2df20b1f4ac357298e4f39798f7a4245f5fc117221de7a74769ff53a8
2020-05-29 15:11:54.411-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:11:59.038-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=7, Round=0}, hash=0x89494f654d37e4a009467a91a69853aecbc8a39773858020c5a6f9d89b630aff
2020-05-29 15:11:59.411-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.453-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.453-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.454-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.454-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.454-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.454-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.454-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:00.455-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:04.019-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=8, Round=0}, hash=0x9cb3192a37eb341d33ee7daff7418eb9cc3842482c327ae3379501881784f729
2020-05-29 15:12:05.455-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
2020-05-29 15:12:09.021-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=9, Round=0}, hash=0xe122b4f4271ffaa785dea0097c4b22209b3958702028cd75094d37fb9c8d624d
2020-05-29 15:12:10.456-06:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, wait for peers.
^C2020-05-29 15:12:14.020-06:00 | pool-10-thread-1 | INFO  | IbftRound | Importing block to chain. round=ConsensusRoundIdentifier{Sequence=10, Round=0}, hash=0x99d83bec390363b0de5997e9ec742f5abdcc6e710f0ce61a2109b0642a9a3c18
2020-05-29 15:12:14.023-06:00 | pool-10-thread-1 | INFO  | IbftProcessor | Shutting down IBFT event processor
2020-05-29 15:12:14.025-06:00 | Thread-1 | INFO  | DefaultSynchronizer | Stopping synchronizer
2020-05-29 15:12:14.026-06:00 | Thread-1 | INFO  | NetworkRunner | Stopping Network.
2020-05-29 15:12:14.029-06:00 | Thread-1 | INFO  | EthProtocolManager | Stopping eth Subprotocol.
2020-05-29 15:12:14.030-06:00 | Thread-1 | INFO  | EthProtocolManager | eth Subprotocol stopped.
2020-05-29 15:12:14.030-06:00 | Thread-1 | INFO  | NetworkRunner | Network stopped.
2020-05-29 15:12:14.030-06:00 | Thread-1 | INFO  | AutoTransactionLogBloomCachingService | Shutting down Auto transaction logs caching service.
2020-05-29 15:12:14.031-06:00 | Thread-1 | INFO  | NatService | No NAT environment detected so no service could be stopped


PEER NODE LOGS:


2020-05-29 14:59:17.048-06:00 | main | INFO  | AltBN128PairingPrecompiledContract | Using native alt bn128
2020-05-29 14:59:18.467-06:00 | main | INFO  | SECP256K1 | Using native secp256k1
2020-05-29 14:59:18.475-06:00 | main | INFO  | Besu | Starting Besu version: besu/v1.4.6-dev-ffa8745d/linux-x86_64/zulu-java-13
2020-05-29 14:59:18.864-06:00 | main | INFO  | Besu | Connecting to 1 static nodes.
2020-05-29 14:59:18.872-06:00 | main | INFO  | Besu | Security Module: localfile
2020-05-29 14:59:18.943-06:00 | main | INFO  | KeyPairUtil | Loaded public key 0xbf3f0cdcafe2f58b214f9f15027904b2bef37a9f6f6b0b1113ce11e09b298c61353c6acaa173f56362ec32f4ebd1474c876bfd1932eb596b10a64cf6930a37fe from /path/to/build/install/besu/key
2020-05-29 14:59:18.977-06:00 | main | INFO  | RocksDBKeyValueStorageFactory | No existing database detected at /path/to/build/install/besu. Using version 1
2020-05-29 14:59:19.423-06:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [ConstantinopleFix: 0]
2020-05-29 14:59:19.606-06:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2020-05-29 14:59:19.690-06:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
2020-05-29 14:59:19.691-06:00 | main | INFO  | NatService | No NAT environment detected so no service could be started
2020-05-29 14:59:19.691-06:00 | main | INFO  | NetworkRunner | Starting Network.
2020-05-29 14:59:19.805-06:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0:0:0:0:0:0:0:0:30303.
2020-05-29 14:59:19.807-06:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2020-05-29 14:59:19.925-06:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0:0:0:0:0:0:0:0 and port=30303
2020-05-29 14:59:19.929-06:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0:0:0:0:0:0:0:0:30303
2020-05-29 14:59:19.978-06:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://bf3f0cdcafe2f58b214f9f15027904b2bef37a9f6f6b0b1113ce11e09b298c61353c6acaa173f56362ec32f4ebd1474c876bfd1932eb596b10a64cf6930a37fe@127.0.0.1:30303
2020-05-29 14:59:19.978-06:00 | main | INFO  | DefaultP2PNetwork | Node address 0x4d67bc82a63dc4837b966b9219bdb247c392b255
2020-05-29 14:59:19.983-06:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2020-05-29 14:59:19.985-06:00 | main | INFO  | FullSyncDownloader | Starting full sync.
2020-05-29 14:59:19.988-06:00 | main | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2020-05-29 14:59:20.088-06:00 | main | INFO  | Runner | Ethereum main loop is up.
2020-05-29 14:59:20.095-06:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
2020-05-29 14:59:24.166-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.167-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.168-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.168-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.169-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.169-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.170-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.170-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.170-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.171-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.171-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.172-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:24.172-06:00 | nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2020-05-29 14:59:27.731-06:00 | nioEventLoopGroup-3-1 | INFO  | BlockPropagationManager | Saving announced block 8 (0x9cb3192a37eb341d33ee7daff7418eb9cc3842482c327ae3379501881784f729) for future import
2020-05-29 14:59:29.178-06:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer 0xfe639f8c0e7fc79ffd... at block 0
2020-05-29 14:59:29.228-06:00 | EthScheduler-Services-2 (validateHeadersJoin) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
	at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:141) ~[?:?]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointRange.getEnd(CheckpointRange.java:58) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:50) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:26) ~[besu-eth-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.FlatMapProcessor.processNextInput(FlatMapProcessor.java:32) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.6-SNAPSHOT.jar:1.4.6-dev-ffa8745d]
	... 5 more

**Comment by NicolasMassart** [comment]
Some important fixes were pushed to the latest version of Besu (on master brabch) that may have some relationship with your issue. I'm not 100% sure it will help but that's worth trying imo.
We will backport these fixes in the 1.4.6 release but for now you could try the 1.4.7 (it's dev SNAPSHOT version so be aware that it could crash something). Please let me know if this helps.

**Comment by Tectract** [comment]
Thank you. I will pull the latest master and build again. 

I'm suspecting that these bugs are related to subtle difference in the open-source implementation of Java (OpenJDK Zulu) that I'm using, but I also find that somewhat surprising. It's interesting that the tests all pass but then it fails in a production environment. Will report back soon.

**Comment by NicolasMassart** [comment]
Hi,
there's a new besu-1.4.7-SNAPSHOT version as we pushed some critical fixes in the master. Could you try to update to latest dev version and tell me if this happens please?
Thanks.

**Comment by Tectract** [comment]
Hmmmm, I don't see dev branch or 1.4.7 tagged release, lol. Might still be private.

**Comment by MadelineMurray** [comment]
@Tectract - we use trunk based development so maser is the dev branch.  If you rebuild using master, you'll have the fixes @NicolasMassart is referring to.

**Comment by Tectract** [comment]
Hi there. Checking in. I have updated to the newest master, 9c37887. 

Problem remains unsolved for me, sadly.

peer machine still says:

2020-06-02 14:26:33.097-06:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer 0xb4f4751830a6a7ca7a... at block 0
2020-06-02 14:26:33.186-06:00 | EthScheduler-Services-2 (validateHeadersJoin) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]


I checked the firewalls on both machines, no issues there. I'm scratching my head trying to figure out what's going on here. This is with a full re-install, new keys, new genesis.json extraData. Is there a tool I can use to insert a breakpoint or anything to help investigate / report on the data state for you guys?

**Comment by arash009** [comment]
@Tectract just to confirm, have both nodes been upgraded to the commit mentioned or is the bootnode still on 1.4.1? We don't expect there to be any issues with different versions, but just want to be clear on your setup.

**Comment by Tectract** [comment]
Yes I upgraded both bootnode and peer node, both are on release 9c37887 now. 

Thank you.

**Comment by Tectract** [comment]
Nope. Exact same error occurred. 

> validateHeadersJoin

>> java.util.NoSuchElementException: No value present

It appears that somewhere, an .isPresent()? function call may be needed, in the validateHeadersJoin part of PipelineChainDownloader. 

I wasn't able to see the last five error lines because of this:

> ... 5 more

Any way to get a more complete stack trace here?

**Comment by NicolasMassart** [comment]
You may try to override log4j file  (as explained here https://besu.hyperledger.org/en/stable/HowTo/Monitor/Logging/#advanced-custom-logging )with one not containing the restriction on 5 last lines
Currently it is `<PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSSZZZ} | %t | %-5level | %c{1} | %msg%n" />` as the `%-5level` is what makes the last 5 lines not visible (see https://stackoverflow.com/questions/37206067/log4j-not-printing-complete-stack-trace )

**Comment by Tectract** [comment]
How do I alter that file so I can see the last five lines of the output please?

**Comment by Tectract** [comment]
OK I copied the [default log4j2.xml file](https://github.com/hyperledger/besu/blob/master/besu/src/main/resources/log4j2.xml) into my directory and removed the %-5level part. Now my run string on the peer node is:

LOG4J_CONFIGURATION_FILE=./debug.xml besu --genesis-file=./GBA_IBFT_genesis.json

No change. Debug stack trace still shows "	... 5 more" at the end, instead of showing the important last five lines which contain the actual function call and filename where the error originated from. Maybe hiding the crucial last 5 lines of stack trace debug output was not a good idea. Just a suggestion.

Still confused about why we can't start the GBA blockchain because of this unresolved critical bug on linux system. We have members buying new hardware to run nodes all over the country, but we can't run them.

**Comment by ajsutton** [comment]
The "... 5 more" indicates that the remaining lines are the same as the last five lines of the wrapping exception so you are getting the complete stack trace printed.  The `%-5level` is just adding spacing to the level (INFO, ERROR etc) to 5 characters so the logs line up better.

**Comment by Tectract** [comment]
Ok well then the error from the last line is 

at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.7-SNAPSHOT.jar:1.4.7-dev-9c37887d]

Hopefully we can try to figure out if there's a missing dependency or something going on here. I know Java is supposed to be largely OS-independent... Not sure what's going on.

**Comment by ajsutton** [comment]
@Tectract Sorry for the difficulty you're having.  I've had a look into this and the exception your seeing is a bit of a red herring - one of the blocks being downloaded in the sync is invalid and the exception you're getting is happening as we try to create the `BlockInvalidException`.  #1049 will stop the exception from happening, but the block will still be considered invalid and the peer disconnected, so we need to work out why you somehow have a blockchain with invalid blocks.

Given that you reproduced this with empty databases and the very first block is being considered invalid it's most likely that the two nodes are somehow running with different genesis configurations.  Could you give me the exact commands you're running to start both the boot node and the peer node please?

Also, the logs you provided when rerunning after deleting the database have timestamps which show the bootnode running around an hour after the peer node ran. Given those timings the peer can't have been trying to download from that boot node.  Alternatively, if this is being run on two different machines (or virtual machines/docker instances) it's possible that the block is being rejected because the two clocks are out of sync and so the received block is seen as being either from the future or too far in the future.

So could you confirm the clocks are in sync and if so, please try to delete the database directories again and ensure we get the two logs from the same run.

Thanks.

**Comment by Tectract** [comment]
You know what I think the problem could be clock sync. Let me play with ntpd and try again.

**Comment by Tectract** [comment]
Solved! Thank you, I was pulling out my hair on this one and I just needed someone else's eyeballs on the logs I guess! GBA blockchain running in basic IBFT mode.

They had some fancy validator reward / staking contract on their earlier genesis block and PoA implementation so now I need to test validator add / remove and then figure out that validator staking contract. Thank you!

**Comment by ajsutton** [comment]
Great to hear it's working.  It's always a challenge when you get misleading error messages like this one so nice to get it fixed.

**Comment by CherryDT** [comment]
Hi, I'm seeing the same error with current Besu version. Any idea what could be the issue now? After all, #1049 was already merged a year ago.

**Comment by CherryDT** [comment]
Hi, do you have any update on this?

**Comment by Tectract** [comment]
> You know what I think the problem could be clock sync. Let me play with ntpd and try again.

I believe this issue was solved for me by syncing my clock via ntpd commands, specifically I think it was something like this:

    sudo service ntp stop
    sudo ntpd -gq
    sudo service ntp start
